### ISSUE TITLE
Parser ignores prefix

### ISSUE THREAD

**Issue by bugproof** [teraa/IrcMessageParser#2]
Hi, I wanted to use it for my twitch chatbot but the parser ignores prefix completely i.e.

**:[user]![user]@[user].tmi.twitch.tv** PRIVMSG #<channel> :This is a sample message

The bold part is completely ignored.

**Comment by teraa** [comment]
Hi, I've added a new record type `MessagePrefix` which contains relevant information from the prefix. The prefix was previously contained unparsed in the `Hostmask` property of the message.

The update addressing this is available as a preview package, version `2.0.0-alpha.46` on both [GitHub Packages](https://github.com/teraa/IrcMessageParser/packages/537268) and [NuGet](https://www.nuget.org/packages/Teraa.IrcMessageParser).

**Comment by bugproof** [comment]
Thanks it works now(: The `Hostmask` previously was `null` for me.
